### PR TITLE
Feature/pianoroll startendpoint

### LINKED ISSUE #71: Start and End Point Selection Piano Roll
... being able to select one particular section of a score (piano roll), by specifying a starting point and an end point.

### PR DESCRIPTION
**Pull request by vee-L**
The selection behaves in a note-to-note manner, so it plays from the first note you select to the last. If you select by beat, it finds which is the first note corresponding to the selected beat for both start and end, and those are the starting and ending notes. The play/pause buttons behaves similarly (pauses and restarts on a note-by-note basis). The BPM selection is pretty self explanatory.

Closes #71  and #72 .

### CODE REVIEW

**Comment by vee-L** [comment]
I haven't put a maximum on the bpm selection because I didn't know what to put but I can add one if you want.

**Comment by musicus** [comment]
OK. Can you set the maximum to 300 bpm?

**Comment by vee-L** [comment]
The default in the audio controller is 360, should I change that too?

**Comment by musicus** [comment]
The default should be 120 bpm ... adjustable from 30 bpm to 360 bpm (which is fine, but not too many humans can play at that speed).

**Comment by vee-L** [comment]
Is this ok to merge?

**Comment by musicus** [comment]
Merged!

**Pull request merged**
